# Use Maven 3.8.3 with OpenJDK 17 for building the project
FROM maven:3.8.3-openjdk-17 AS build
COPY . /app
WORKDIR /app
RUN mvn clean install

# Use OpenJDK 17 runtime for running the application
FROM eclipse-temurin:17-jdk
COPY --from=build /app/target/*.jar /app/demo.jar
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "demo.jar"]
